theme: jekyll-theme-midnight
# 👋🏾 I'm Dayfah

I'm a visual artist, photographer, streamer, and mad scientist building cool things to wow the world.

## 🎨 My Work

- **Photography:** [Dayfah’s Space](https://link-to-gallery.com)
- **Streaming:** [TheSpeakEasy on Twitch](https://twitch.tv/TheSpeakEasy)
- **AI Assistant Project:** [A.R.I.A. on GitHub](https://github.com/dayfah/aria)


## 🔧 Skills

- 📷 Portrait & street photography
- 🧠 AI automation (n8n, Discord, Shortcuts)
- 🎤 Streaming & content strategy
- 🧪 Science & third-party testing lab builder

## 📫 Let’s Build

- [Instagram](https://instagram.com/dayfah)
- [Email](mailto:Hudhayfahamir@gmail.com)
